# Generated by Django 3.0.8 on 2020-11-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_photoimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
